name = "glow-broadcast"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "BROADCAST_ROOM", class_name = "BroadcastRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["BroadcastRoom"]

[vars]
# Add your shared secret for authentication from Lambda webhooks
WEBHOOK_SECRET = "your-webhook-secret-here"

# Optional: Add allowed origins for WebSocket connections
ALLOWED_ORIGINS = "https://your-app.com,http://localhost:3000"

# Configure routes
[[routes]]
pattern = "broadcast.your-domain.com/*"
zone_name = "your-domain.com" 